/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GeralIndexImport } from './routes/geral/index'

// Create/Update Routes

const GeralIndexRoute = GeralIndexImport.update({
  id: '/geral/',
  path: '/geral/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/geral/': {
      id: '/geral/'
      path: '/geral'
      fullPath: '/geral'
      preLoaderRoute: typeof GeralIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/geral': typeof GeralIndexRoute
}

export interface FileRoutesByTo {
  '/geral': typeof GeralIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/geral/': typeof GeralIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/geral'
  fileRoutesByTo: FileRoutesByTo
  to: '/geral'
  id: '__root__' | '/geral/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  GeralIndexRoute: typeof GeralIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  GeralIndexRoute: GeralIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/geral/"
      ]
    },
    "/geral/": {
      "filePath": "geral/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
